version: '3.8'

services:
  web:
    build:
      context: .
      args:
        # Required for Vite build
        VITE_NHOST_BACKEND_URL: ${VITE_NHOST_BACKEND_URL}
    ports:
      - "${PORT:-4173}:4173"
    env_file:
      - .env
    environment:
      - PORT=4173
