table:
  name: tenant_settings
  schema: public
select_permissions:
  - role: system_admin
    permission:
      columns: '*'
      filter: {}
  - role: admin
    permission:
      columns: '*'
      filter:
        district_id:
          _eq: X-Hasura-District-Id
  - role: district_admin
    permission:
      columns: '*'
      filter:
        _and:
          - district_id:
              _eq: X-Hasura-District-Id
          - school_id:
              _is_null: true
  - role: school_admin
    permission:
      columns: '*'
      filter:
        school_id:
          _eq: X-Hasura-School-Id
insert_permissions:
  - role: system_admin
    permission:
      check: {}
      columns: '*'
  - role: admin
    permission:
      check:
        district_id:
          _eq: X-Hasura-District-Id
      columns: '*'
  - role: district_admin
    permission:
      check:
        _and:
          - district_id:
              _eq: X-Hasura-District-Id
          - school_id:
              _is_null: true
      columns: '*'
  - role: school_admin
    permission:
      check:
        school_id:
          _eq: X-Hasura-School-Id
      columns: '*'
update_permissions:
  - role: system_admin
    permission:
      columns: '*'
      filter: {}
      check: {}
  - role: admin
    permission:
      columns: '*'
      filter:
        district_id:
          _eq: X-Hasura-District-Id
      check:
        district_id:
          _eq: X-Hasura-District-Id
  - role: district_admin
    permission:
      columns: '*'
      filter:
        _and:
          - district_id:
              _eq: X-Hasura-District-Id
          - school_id:
              _is_null: true
      check:
        _and:
          - district_id:
              _eq: X-Hasura-District-Id
          - school_id:
              _is_null: true
  - role: school_admin
    permission:
      columns: '*'
      filter:
        school_id:
          _eq: X-Hasura-School-Id
      check:
        school_id:
          _eq: X-Hasura-School-Id
