table:
  name: tenant_settings
  schema: public
select_permissions:
  - role: system_admin
    permission:
      columns: '*'
      filter: {}
  - role: admin
    permission:
      columns: '*'
      filter:
        organization_id:
          _eq: X-Hasura-Organization-Id
  - role: district_admin
    permission:
      columns: '*'
      filter:
        organization_id:
          _eq: X-Hasura-Organization-Id
  - role: school_admin
    permission:
      columns: '*'
      filter:
        organization_id:
          _eq: X-Hasura-Organization-Id
        _or:
          - school_id:
              _eq: X-Hasura-School-Id
          - school_id:
              _is_null: true
insert_permissions:
  - role: admin
    permission:
      columns:
        - organization_id
        - school_id
        - branding
        - settings
      check:
        organization_id:
          _eq: X-Hasura-Organization-Id
  - role: district_admin
    permission:
      columns:
        - organization_id
        - school_id
        - branding
        - settings
      check:
        organization_id:
          _eq: X-Hasura-Organization-Id
  - role: school_admin
    permission:
      columns:
        - organization_id
        - school_id
        - branding
        - settings
      check:
        organization_id:
          _eq: X-Hasura-Organization-Id
        _or:
          - school_id:
              _eq: X-Hasura-School-Id
          - school_id:
              _is_null: true
update_permissions:
  - role: admin
    permission:
      columns:
        - branding
        - settings
      filter:
        organization_id:
          _eq: X-Hasura-Organization-Id
      check: {}
  - role: district_admin
    permission:
      columns:
        - branding
        - settings
      filter:
        organization_id:
          _eq: X-Hasura-Organization-Id
      check: {}
  - role: school_admin
    permission:
      columns:
        - branding
        - settings
      filter:
        organization_id:
          _eq: X-Hasura-Organization-Id
        _or:
          - school_id:
              _eq: X-Hasura-School-Id
          - school_id:
              _is_null: true
      check: {}
