table:
  name: partner_incentive_applications
  schema: public
select_permissions:
  - role: system_admin
    permission:
      columns: '*'
      filter: {}
  - role: admin
    permission:
      columns: '*'
      filter: {}
