table:
  name: partner_incentive_applications
  schema: public
object_relationships:
  - name: incentive
    using:
      foreign_key_constraint_on: incentive_id
select_permissions:
  - role: system_admin
    permission:
      columns: '*'
      filter: {}
  - role: admin
    permission:
      columns: '*'
      filter:
        organization_id:
          _eq: X-Hasura-Organization-Id
  - role: district_admin
    permission:
      columns: '*'
      filter:
        organization_id:
          _eq: X-Hasura-Organization-Id
  - role: school_admin
    permission:
      columns: '*'
      filter:
        organization_id:
          _eq: X-Hasura-Organization-Id
  - role: partner
    permission:
      columns: '*'
      filter:
        organization_id:
          _eq: X-Hasura-Organization-Id
        partner_id:
          _eq: X-Hasura-User-Id
insert_permissions:
  - role: partner
    permission:
      columns:
        - organization_id
        - incentive_id
        - partner_id
      check:
        organization_id:
          _eq: X-Hasura-Organization-Id
        partner_id:
          _eq: X-Hasura-User-Id
update_permissions:
  - role: admin
    permission:
      columns:
        - status
        - payout
      filter:
        organization_id:
          _eq: X-Hasura-Organization-Id
      check: {}
